### PR TITLE
8296480: java/security/cert/pkix/policyChanges/TestPolicy.java is failing

### PR DESCRIPTION
**Pull request by nibjen**
---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8296480](https://bugs.openjdk.org/browse/JDK-8296480): java/security/cert/pkix/policyChanges/TestPolicy.java is failing

### Reviewers
 * [Sean Coffey](https://openjdk.org/census#coffeys) (@coffeys - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk19u pull/69/head:pull/69` \
`$ git checkout pull/69`

Update a local copy of the PR: \
`$ git checkout pull/69` \
`$ git pull https://git.openjdk.org/jdk19u pull/69/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 69`

View PR using the GUI difftool: \
`$ git pr show -t 69`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk19u/pull/69.diff">https://git.openjdk.org/jdk19u/pull/69.diff</a>

</details>

### CODE REVIEW

**Comment by nibjen** [comment]
https://mach5.us.oracle.com/mdash/jobs/jnibedit-jdk19u-cpu-20221116-1017-38572195/results?search=*java%2Fsecurity%2Fcert%2Fpkix%2FpolicyChanges%2FTestPolicy.java*

**Review by coffeys — APPROVED** [review]
LGTM

**Pull request closed without merging**
