### PR TITLE
8287906: Rewrite of GitHub Actions (GHA) sanity tests

### PR DESCRIPTION
**Pull request by gdams**
backport [JDK-8287906](https://bugs.openjdk.org/browse/JDK-8287906) - clean

---------
### Progress
- [x] Change must not contain extraneous whitespace
- [x] Commit message must refer to an issue

### Issue
 * [JDK-8287906](https://bugs.openjdk.org/browse/JDK-8287906): Rewrite of GitHub Actions (GHA) sanity tests

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jdk19u pull/4/head:pull/4` \
`$ git checkout pull/4`

Update a local copy of the PR: \
`$ git checkout pull/4` \
`$ git pull https://git.openjdk.org/jdk19u pull/4/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 4`

View PR using the GUI difftool: \
`$ git pr show -t 4`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jdk19u/pull/4.diff">https://git.openjdk.org/jdk19u/pull/4.diff</a>

</details>

### CODE REVIEW

**Comment by RealCLanger** [comment]
Looks good. The errors observed should be fixed with:
1. 8289251: ProblemList java/lang/ref/OOMEInReferenceHandler.java which is not yet merged into jdk19u
2. 8287902: UnreadableRB case in MissingResourceCauseTest is not working reliably on Windows - this was done only in head jdk so far, I've triggered a backport to jdk19.

**Comment by gdams** [comment]
Thanks @RealCLanger I'm happy to backport that problemlist PR too

**Pull request closed without merging**
